//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitSoftBusiness.VehiculoPropietarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", ConfigurationName="VehiculoPropietarioWS.VehiculoPropietario")]
    public interface VehiculoPropietario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarR" +
            "elacionesRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarR" +
            "elacionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesResponse listarRelaciones(TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarR" +
            "elacionesRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarR" +
            "elacionesResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesResponse> listarRelacionesAsync(TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/obtener" +
            "RelacionPorIdRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/obtener" +
            "RelacionPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdResponse obtenerRelacionPorId(TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/obtener" +
            "RelacionPorIdRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/obtener" +
            "RelacionPorIdResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdResponse> obtenerRelacionPorIdAsync(TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/modific" +
            "arRelacionRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/modific" +
            "arRelacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionResponse modificarRelacion(TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/modific" +
            "arRelacionRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/modific" +
            "arRelacionResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionResponse> modificarRelacionAsync(TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/elimina" +
            "rRelacionRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/elimina" +
            "rRelacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionResponse eliminarRelacion(TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/elimina" +
            "rRelacionRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/elimina" +
            "rRelacionResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionResponse> eliminarRelacionAsync(TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/inserta" +
            "rRelacionRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/inserta" +
            "rRelacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionResponse insertarRelacion(TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/inserta" +
            "rRelacionRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/inserta" +
            "rRelacionResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionResponse> insertarRelacionAsync(TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarV" +
            "ehiculosPorPropietarioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarV" +
            "ehiculosPorPropietarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioResponse listarVehiculosPorPropietario(TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarV" +
            "ehiculosPorPropietarioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarV" +
            "ehiculosPorPropietarioResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioResponse> listarVehiculosPorPropietarioAsync(TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarP" +
            "ropietariosPorVehiculoRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarP" +
            "ropietariosPorVehiculoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoResponse listarPropietariosPorVehiculo(TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarP" +
            "ropietariosPorVehiculoRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/VehiculoPropietario/listarP" +
            "ropietariosPorVehiculoResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoResponse> listarPropietariosPorVehiculoAsync(TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/")]
    public partial class vehiculoPropietarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int id_propietarioField;
        
        private bool id_propietarioFieldSpecified;
        
        private int id_vehiculoField;
        
        private bool id_vehiculoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_propietario {
            get {
                return this.id_propietarioField;
            }
            set {
                this.id_propietarioField = value;
                this.RaisePropertyChanged("id_propietario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_propietarioSpecified {
            get {
                return this.id_propietarioFieldSpecified;
            }
            set {
                this.id_propietarioFieldSpecified = value;
                this.RaisePropertyChanged("id_propietarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_vehiculo {
            get {
                return this.id_vehiculoField;
            }
            set {
                this.id_vehiculoField = value;
                this.RaisePropertyChanged("id_vehiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_vehiculoSpecified {
            get {
                return this.id_vehiculoFieldSpecified;
            }
            set {
                this.id_vehiculoFieldSpecified = value;
                this.RaisePropertyChanged("id_vehiculoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/")]
    public partial class propietarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string direccionField;
        
        private int dniField;
        
        private bool dniFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dniSpecified {
            get {
                return this.dniFieldSpecified;
            }
            set {
                this.dniFieldSpecified = value;
                this.RaisePropertyChanged("dniSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/")]
    public partial class vehiculoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool anhoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string marcaField;
        
        private string modeloField;
        
        private string placaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anhoSpecified {
            get {
                return this.anhoFieldSpecified;
            }
            set {
                this.anhoFieldSpecified = value;
                this.RaisePropertyChanged("anhoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRelaciones", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRelacionesRequest {
        
        public listarRelacionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRelacionesResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRelacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.VehiculoPropietarioWS.vehiculoPropietarioDTO[] @return;
        
        public listarRelacionesResponse() {
        }
        
        public listarRelacionesResponse(TransitSoftBusiness.VehiculoPropietarioWS.vehiculoPropietarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerRelacionPorId", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerRelacionPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerRelacionPorIdRequest() {
        }
        
        public obtenerRelacionPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerRelacionPorIdResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerRelacionPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.VehiculoPropietarioWS.vehiculoPropietarioDTO @return;
        
        public obtenerRelacionPorIdResponse() {
        }
        
        public obtenerRelacionPorIdResponse(TransitSoftBusiness.VehiculoPropietarioWS.vehiculoPropietarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRelacion", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_vehiculo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_propietario;
        
        public modificarRelacionRequest() {
        }
        
        public modificarRelacionRequest(int id, int id_vehiculo, int id_propietario) {
            this.id = id;
            this.id_vehiculo = id_vehiculo;
            this.id_propietario = id_propietario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarRelacionResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarRelacionResponse() {
        }
        
        public modificarRelacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRelacion", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarRelacionRequest() {
        }
        
        public eliminarRelacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRelacionResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarRelacionResponse() {
        }
        
        public eliminarRelacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRelacion", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_vehiculo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_propietario;
        
        public insertarRelacionRequest() {
        }
        
        public insertarRelacionRequest(int id_vehiculo, int id_propietario) {
            this.id_vehiculo = id_vehiculo;
            this.id_propietario = id_propietario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRelacionResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarRelacionResponse() {
        }
        
        public insertarRelacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVehiculosPorPropietario", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVehiculosPorPropietarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_propietario;
        
        public listarVehiculosPorPropietarioRequest() {
        }
        
        public listarVehiculosPorPropietarioRequest(int id_propietario) {
            this.id_propietario = id_propietario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVehiculosPorPropietarioResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVehiculosPorPropietarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.VehiculoPropietarioWS.vehiculoDTO[] @return;
        
        public listarVehiculosPorPropietarioResponse() {
        }
        
        public listarVehiculosPorPropietarioResponse(TransitSoftBusiness.VehiculoPropietarioWS.vehiculoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPropietariosPorVehiculo", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPropietariosPorVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_vehiculo;
        
        public listarPropietariosPorVehiculoRequest() {
        }
        
        public listarPropietariosPorVehiculoRequest(int id_vehiculo) {
            this.id_vehiculo = id_vehiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPropietariosPorVehiculoResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPropietariosPorVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.VehiculoPropietarioWS.propietarioDTO[] @return;
        
        public listarPropietariosPorVehiculoResponse() {
        }
        
        public listarPropietariosPorVehiculoResponse(TransitSoftBusiness.VehiculoPropietarioWS.propietarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehiculoPropietarioChannel : TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoPropietarioClient : System.ServiceModel.ClientBase<TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario>, TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario {
        
        public VehiculoPropietarioClient() {
        }
        
        public VehiculoPropietarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoPropietarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoPropietarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoPropietarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.listarRelaciones(TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest request) {
            return base.Channel.listarRelaciones(request);
        }
        
        public TransitSoftBusiness.VehiculoPropietarioWS.vehiculoPropietarioDTO[] listarRelaciones() {
            TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest();
            TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).listarRelaciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.listarRelacionesAsync(TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest request) {
            return base.Channel.listarRelacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesResponse> listarRelacionesAsync() {
            TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.listarRelacionesRequest();
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).listarRelacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.obtenerRelacionPorId(TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest request) {
            return base.Channel.obtenerRelacionPorId(request);
        }
        
        public TransitSoftBusiness.VehiculoPropietarioWS.vehiculoPropietarioDTO obtenerRelacionPorId(int id) {
            TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest();
            inValue.id = id;
            TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).obtenerRelacionPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.obtenerRelacionPorIdAsync(TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest request) {
            return base.Channel.obtenerRelacionPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdResponse> obtenerRelacionPorIdAsync(int id) {
            TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.obtenerRelacionPorIdRequest();
            inValue.id = id;
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).obtenerRelacionPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.modificarRelacion(TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest request) {
            return base.Channel.modificarRelacion(request);
        }
        
        public int modificarRelacion(int id, int id_vehiculo, int id_propietario) {
            TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest();
            inValue.id = id;
            inValue.id_vehiculo = id_vehiculo;
            inValue.id_propietario = id_propietario;
            TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).modificarRelacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.modificarRelacionAsync(TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest request) {
            return base.Channel.modificarRelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionResponse> modificarRelacionAsync(int id, int id_vehiculo, int id_propietario) {
            TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.modificarRelacionRequest();
            inValue.id = id;
            inValue.id_vehiculo = id_vehiculo;
            inValue.id_propietario = id_propietario;
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).modificarRelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.eliminarRelacion(TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest request) {
            return base.Channel.eliminarRelacion(request);
        }
        
        public int eliminarRelacion(int id) {
            TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest();
            inValue.id = id;
            TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).eliminarRelacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.eliminarRelacionAsync(TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest request) {
            return base.Channel.eliminarRelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionResponse> eliminarRelacionAsync(int id) {
            TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.eliminarRelacionRequest();
            inValue.id = id;
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).eliminarRelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.insertarRelacion(TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest request) {
            return base.Channel.insertarRelacion(request);
        }
        
        public int insertarRelacion(int id_vehiculo, int id_propietario) {
            TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest();
            inValue.id_vehiculo = id_vehiculo;
            inValue.id_propietario = id_propietario;
            TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).insertarRelacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.insertarRelacionAsync(TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest request) {
            return base.Channel.insertarRelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionResponse> insertarRelacionAsync(int id_vehiculo, int id_propietario) {
            TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.insertarRelacionRequest();
            inValue.id_vehiculo = id_vehiculo;
            inValue.id_propietario = id_propietario;
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).insertarRelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.listarVehiculosPorPropietario(TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest request) {
            return base.Channel.listarVehiculosPorPropietario(request);
        }
        
        public TransitSoftBusiness.VehiculoPropietarioWS.vehiculoDTO[] listarVehiculosPorPropietario(int id_propietario) {
            TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest();
            inValue.id_propietario = id_propietario;
            TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).listarVehiculosPorPropietario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.listarVehiculosPorPropietarioAsync(TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest request) {
            return base.Channel.listarVehiculosPorPropietarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioResponse> listarVehiculosPorPropietarioAsync(int id_propietario) {
            TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.listarVehiculosPorPropietarioRequest();
            inValue.id_propietario = id_propietario;
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).listarVehiculosPorPropietarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoResponse TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.listarPropietariosPorVehiculo(TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest request) {
            return base.Channel.listarPropietariosPorVehiculo(request);
        }
        
        public TransitSoftBusiness.VehiculoPropietarioWS.propietarioDTO[] listarPropietariosPorVehiculo(int id_vehiculo) {
            TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest();
            inValue.id_vehiculo = id_vehiculo;
            TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoResponse retVal = ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).listarPropietariosPorVehiculo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoResponse> TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario.listarPropietariosPorVehiculoAsync(TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest request) {
            return base.Channel.listarPropietariosPorVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoResponse> listarPropietariosPorVehiculoAsync(int id_vehiculo) {
            TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest inValue = new TransitSoftBusiness.VehiculoPropietarioWS.listarPropietariosPorVehiculoRequest();
            inValue.id_vehiculo = id_vehiculo;
            return ((TransitSoftBusiness.VehiculoPropietarioWS.VehiculoPropietario)(this)).listarPropietariosPorVehiculoAsync(inValue);
        }
    }
}
