//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitSoftBusiness.PropietarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", ConfigurationName="PropietarioWS.Propietario")]
    public interface Propietario {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/listarPropietar" +
            "iosRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/listarPropietar" +
            "iosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.PropietarioWS.listarPropietariosResponse listarPropietarios(TransitSoftBusiness.PropietarioWS.listarPropietariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/listarPropietar" +
            "iosRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/listarPropietar" +
            "iosResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.listarPropietariosResponse> listarPropietariosAsync(TransitSoftBusiness.PropietarioWS.listarPropietariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/modificarPropie" +
            "tarioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/modificarPropie" +
            "tarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.PropietarioWS.modificarPropietarioResponse modificarPropietario(TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/modificarPropie" +
            "tarioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/modificarPropie" +
            "tarioResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.modificarPropietarioResponse> modificarPropietarioAsync(TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/insertarPropiet" +
            "arioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/insertarPropiet" +
            "arioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.PropietarioWS.insertarPropietarioResponse insertarPropietario(TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/insertarPropiet" +
            "arioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/insertarPropiet" +
            "arioResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.insertarPropietarioResponse> insertarPropietarioAsync(TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/obtenerPropieta" +
            "rioPorIdRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/obtenerPropieta" +
            "rioPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdResponse obtenerPropietarioPorId(TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/obtenerPropieta" +
            "rioPorIdRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/obtenerPropieta" +
            "rioPorIdResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdResponse> obtenerPropietarioPorIdAsync(TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/eliminarPropiet" +
            "arioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/eliminarPropiet" +
            "arioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.PropietarioWS.eliminarPropietarioResponse eliminarPropietario(TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/eliminarPropiet" +
            "arioRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Propietario/eliminarPropiet" +
            "arioResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.eliminarPropietarioResponse> eliminarPropietarioAsync(TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/")]
    public partial class propietarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string direccionField;
        
        private int dniField;
        
        private bool dniFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dniSpecified {
            get {
                return this.dniFieldSpecified;
            }
            set {
                this.dniFieldSpecified = value;
                this.RaisePropertyChanged("dniSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPropietarios", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPropietariosRequest {
        
        public listarPropietariosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPropietariosResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPropietariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.PropietarioWS.propietarioDTO[] @return;
        
        public listarPropietariosResponse() {
        }
        
        public listarPropietariosResponse(TransitSoftBusiness.PropietarioWS.propietarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPropietario", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPropietarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        public modificarPropietarioRequest() {
        }
        
        public modificarPropietarioRequest(int id, int dni, string nombres, string apellidos, string direccion) {
            this.id = id;
            this.dni = dni;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPropietarioResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPropietarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPropietarioResponse() {
        }
        
        public modificarPropietarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPropietario", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPropietarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        public insertarPropietarioRequest() {
        }
        
        public insertarPropietarioRequest(int dni, string nombres, string apellidos, string direccion) {
            this.dni = dni;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPropietarioResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPropietarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPropietarioResponse() {
        }
        
        public insertarPropietarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPropietarioPorId", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPropietarioPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPropietarioPorIdRequest() {
        }
        
        public obtenerPropietarioPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPropietarioPorIdResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPropietarioPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.PropietarioWS.propietarioDTO @return;
        
        public obtenerPropietarioPorIdResponse() {
        }
        
        public obtenerPropietarioPorIdResponse(TransitSoftBusiness.PropietarioWS.propietarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPropietario", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPropietarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarPropietarioRequest() {
        }
        
        public eliminarPropietarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPropietarioResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPropietarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPropietarioResponse() {
        }
        
        public eliminarPropietarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PropietarioChannel : TransitSoftBusiness.PropietarioWS.Propietario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropietarioClient : System.ServiceModel.ClientBase<TransitSoftBusiness.PropietarioWS.Propietario>, TransitSoftBusiness.PropietarioWS.Propietario {
        
        public PropietarioClient() {
        }
        
        public PropietarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropietarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropietarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropietarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.PropietarioWS.listarPropietariosResponse TransitSoftBusiness.PropietarioWS.Propietario.listarPropietarios(TransitSoftBusiness.PropietarioWS.listarPropietariosRequest request) {
            return base.Channel.listarPropietarios(request);
        }
        
        public TransitSoftBusiness.PropietarioWS.propietarioDTO[] listarPropietarios() {
            TransitSoftBusiness.PropietarioWS.listarPropietariosRequest inValue = new TransitSoftBusiness.PropietarioWS.listarPropietariosRequest();
            TransitSoftBusiness.PropietarioWS.listarPropietariosResponse retVal = ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).listarPropietarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.listarPropietariosResponse> TransitSoftBusiness.PropietarioWS.Propietario.listarPropietariosAsync(TransitSoftBusiness.PropietarioWS.listarPropietariosRequest request) {
            return base.Channel.listarPropietariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.listarPropietariosResponse> listarPropietariosAsync() {
            TransitSoftBusiness.PropietarioWS.listarPropietariosRequest inValue = new TransitSoftBusiness.PropietarioWS.listarPropietariosRequest();
            return ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).listarPropietariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.PropietarioWS.modificarPropietarioResponse TransitSoftBusiness.PropietarioWS.Propietario.modificarPropietario(TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest request) {
            return base.Channel.modificarPropietario(request);
        }
        
        public int modificarPropietario(int id, int dni, string nombres, string apellidos, string direccion) {
            TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest inValue = new TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest();
            inValue.id = id;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.direccion = direccion;
            TransitSoftBusiness.PropietarioWS.modificarPropietarioResponse retVal = ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).modificarPropietario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.modificarPropietarioResponse> TransitSoftBusiness.PropietarioWS.Propietario.modificarPropietarioAsync(TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest request) {
            return base.Channel.modificarPropietarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.modificarPropietarioResponse> modificarPropietarioAsync(int id, int dni, string nombres, string apellidos, string direccion) {
            TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest inValue = new TransitSoftBusiness.PropietarioWS.modificarPropietarioRequest();
            inValue.id = id;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.direccion = direccion;
            return ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).modificarPropietarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.PropietarioWS.insertarPropietarioResponse TransitSoftBusiness.PropietarioWS.Propietario.insertarPropietario(TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest request) {
            return base.Channel.insertarPropietario(request);
        }
        
        public int insertarPropietario(int dni, string nombres, string apellidos, string direccion) {
            TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest inValue = new TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.direccion = direccion;
            TransitSoftBusiness.PropietarioWS.insertarPropietarioResponse retVal = ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).insertarPropietario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.insertarPropietarioResponse> TransitSoftBusiness.PropietarioWS.Propietario.insertarPropietarioAsync(TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest request) {
            return base.Channel.insertarPropietarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.insertarPropietarioResponse> insertarPropietarioAsync(int dni, string nombres, string apellidos, string direccion) {
            TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest inValue = new TransitSoftBusiness.PropietarioWS.insertarPropietarioRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.direccion = direccion;
            return ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).insertarPropietarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdResponse TransitSoftBusiness.PropietarioWS.Propietario.obtenerPropietarioPorId(TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest request) {
            return base.Channel.obtenerPropietarioPorId(request);
        }
        
        public TransitSoftBusiness.PropietarioWS.propietarioDTO obtenerPropietarioPorId(int id) {
            TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest inValue = new TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest();
            inValue.id = id;
            TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdResponse retVal = ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).obtenerPropietarioPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdResponse> TransitSoftBusiness.PropietarioWS.Propietario.obtenerPropietarioPorIdAsync(TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest request) {
            return base.Channel.obtenerPropietarioPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdResponse> obtenerPropietarioPorIdAsync(int id) {
            TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest inValue = new TransitSoftBusiness.PropietarioWS.obtenerPropietarioPorIdRequest();
            inValue.id = id;
            return ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).obtenerPropietarioPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.PropietarioWS.eliminarPropietarioResponse TransitSoftBusiness.PropietarioWS.Propietario.eliminarPropietario(TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest request) {
            return base.Channel.eliminarPropietario(request);
        }
        
        public int eliminarPropietario(int id) {
            TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest inValue = new TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest();
            inValue.id = id;
            TransitSoftBusiness.PropietarioWS.eliminarPropietarioResponse retVal = ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).eliminarPropietario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.eliminarPropietarioResponse> TransitSoftBusiness.PropietarioWS.Propietario.eliminarPropietarioAsync(TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest request) {
            return base.Channel.eliminarPropietarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.PropietarioWS.eliminarPropietarioResponse> eliminarPropietarioAsync(int id) {
            TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest inValue = new TransitSoftBusiness.PropietarioWS.eliminarPropietarioRequest();
            inValue.id = id;
            return ((TransitSoftBusiness.PropietarioWS.Propietario)(this)).eliminarPropietarioAsync(inValue);
        }
    }
}
