//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitSoftBusiness.VehiculoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", ConfigurationName="VehiculoWS.Vehiculo")]
    public interface Vehiculo {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/listarVehiculosReq" +
            "uest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/listarVehiculosRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoWS.listarVehiculosResponse listarVehiculos(TransitSoftBusiness.VehiculoWS.listarVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/listarVehiculosReq" +
            "uest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/listarVehiculosRes" +
            "ponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.listarVehiculosResponse> listarVehiculosAsync(TransitSoftBusiness.VehiculoWS.listarVehiculosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/insertarVehiculoRe" +
            "quest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/insertarVehiculoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoWS.insertarVehiculoResponse insertarVehiculo(TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/insertarVehiculoRe" +
            "quest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/insertarVehiculoRe" +
            "sponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.insertarVehiculoResponse> insertarVehiculoAsync(TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/eliminarVehiculoRe" +
            "quest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/eliminarVehiculoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoWS.eliminarVehiculoResponse eliminarVehiculo(TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/eliminarVehiculoRe" +
            "quest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/eliminarVehiculoRe" +
            "sponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.eliminarVehiculoResponse> eliminarVehiculoAsync(TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/modificarVehiculoR" +
            "equest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/modificarVehiculoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoWS.modificarVehiculoResponse modificarVehiculo(TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/modificarVehiculoR" +
            "equest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/modificarVehiculoR" +
            "esponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.modificarVehiculoResponse> modificarVehiculoAsync(TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/obtenerVehiculoPor" +
            "IdRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/obtenerVehiculoPor" +
            "IdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdResponse obtenerVehiculoPorId(TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/obtenerVehiculoPor" +
            "IdRequest", ReplyAction="http://transitsoftws.services.transitsoft.pucp.edu.pe/Vehiculo/obtenerVehiculoPor" +
            "IdResponse")]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdResponse> obtenerVehiculoPorIdAsync(TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/")]
    public partial class vehiculoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private bool anhoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string marcaField;
        
        private string modeloField;
        
        private string placaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anhoSpecified {
            get {
                return this.anhoFieldSpecified;
            }
            set {
                this.anhoFieldSpecified = value;
                this.RaisePropertyChanged("anhoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVehiculos", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVehiculosRequest {
        
        public listarVehiculosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVehiculosResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.VehiculoWS.vehiculoDTO[] @return;
        
        public listarVehiculosResponse() {
        }
        
        public listarVehiculosResponse(TransitSoftBusiness.VehiculoWS.vehiculoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVehiculo", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anho;
        
        public insertarVehiculoRequest() {
        }
        
        public insertarVehiculoRequest(string placa, string marca, string modelo, int anho) {
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.anho = anho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVehiculoResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVehiculoResponse() {
        }
        
        public insertarVehiculoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVehiculo", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarVehiculoRequest() {
        }
        
        public eliminarVehiculoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVehiculoResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarVehiculoResponse() {
        }
        
        public eliminarVehiculoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVehiculo", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anho;
        
        public modificarVehiculoRequest() {
        }
        
        public modificarVehiculoRequest(int id, string placa, string marca, string modelo, int anho) {
            this.id = id;
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.anho = anho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVehiculoResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarVehiculoResponse() {
        }
        
        public modificarVehiculoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerVehiculoPorId", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerVehiculoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerVehiculoPorIdRequest() {
        }
        
        public obtenerVehiculoPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerVehiculoPorIdResponse", WrapperNamespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerVehiculoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transitsoftws.services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBusiness.VehiculoWS.vehiculoDTO @return;
        
        public obtenerVehiculoPorIdResponse() {
        }
        
        public obtenerVehiculoPorIdResponse(TransitSoftBusiness.VehiculoWS.vehiculoDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehiculoChannel : TransitSoftBusiness.VehiculoWS.Vehiculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoClient : System.ServiceModel.ClientBase<TransitSoftBusiness.VehiculoWS.Vehiculo>, TransitSoftBusiness.VehiculoWS.Vehiculo {
        
        public VehiculoClient() {
        }
        
        public VehiculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoWS.listarVehiculosResponse TransitSoftBusiness.VehiculoWS.Vehiculo.listarVehiculos(TransitSoftBusiness.VehiculoWS.listarVehiculosRequest request) {
            return base.Channel.listarVehiculos(request);
        }
        
        public TransitSoftBusiness.VehiculoWS.vehiculoDTO[] listarVehiculos() {
            TransitSoftBusiness.VehiculoWS.listarVehiculosRequest inValue = new TransitSoftBusiness.VehiculoWS.listarVehiculosRequest();
            TransitSoftBusiness.VehiculoWS.listarVehiculosResponse retVal = ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).listarVehiculos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.listarVehiculosResponse> TransitSoftBusiness.VehiculoWS.Vehiculo.listarVehiculosAsync(TransitSoftBusiness.VehiculoWS.listarVehiculosRequest request) {
            return base.Channel.listarVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.listarVehiculosResponse> listarVehiculosAsync() {
            TransitSoftBusiness.VehiculoWS.listarVehiculosRequest inValue = new TransitSoftBusiness.VehiculoWS.listarVehiculosRequest();
            return ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).listarVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoWS.insertarVehiculoResponse TransitSoftBusiness.VehiculoWS.Vehiculo.insertarVehiculo(TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest request) {
            return base.Channel.insertarVehiculo(request);
        }
        
        public int insertarVehiculo(string placa, string marca, string modelo, int anho) {
            TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest inValue = new TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest();
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.anho = anho;
            TransitSoftBusiness.VehiculoWS.insertarVehiculoResponse retVal = ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).insertarVehiculo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.insertarVehiculoResponse> TransitSoftBusiness.VehiculoWS.Vehiculo.insertarVehiculoAsync(TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest request) {
            return base.Channel.insertarVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.insertarVehiculoResponse> insertarVehiculoAsync(string placa, string marca, string modelo, int anho) {
            TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest inValue = new TransitSoftBusiness.VehiculoWS.insertarVehiculoRequest();
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.anho = anho;
            return ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).insertarVehiculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoWS.eliminarVehiculoResponse TransitSoftBusiness.VehiculoWS.Vehiculo.eliminarVehiculo(TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest request) {
            return base.Channel.eliminarVehiculo(request);
        }
        
        public int eliminarVehiculo(int id) {
            TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest inValue = new TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest();
            inValue.id = id;
            TransitSoftBusiness.VehiculoWS.eliminarVehiculoResponse retVal = ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).eliminarVehiculo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.eliminarVehiculoResponse> TransitSoftBusiness.VehiculoWS.Vehiculo.eliminarVehiculoAsync(TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest request) {
            return base.Channel.eliminarVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.eliminarVehiculoResponse> eliminarVehiculoAsync(int id) {
            TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest inValue = new TransitSoftBusiness.VehiculoWS.eliminarVehiculoRequest();
            inValue.id = id;
            return ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).eliminarVehiculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoWS.modificarVehiculoResponse TransitSoftBusiness.VehiculoWS.Vehiculo.modificarVehiculo(TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest request) {
            return base.Channel.modificarVehiculo(request);
        }
        
        public int modificarVehiculo(int id, string placa, string marca, string modelo, int anho) {
            TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest inValue = new TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest();
            inValue.id = id;
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.anho = anho;
            TransitSoftBusiness.VehiculoWS.modificarVehiculoResponse retVal = ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).modificarVehiculo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.modificarVehiculoResponse> TransitSoftBusiness.VehiculoWS.Vehiculo.modificarVehiculoAsync(TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest request) {
            return base.Channel.modificarVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.modificarVehiculoResponse> modificarVehiculoAsync(int id, string placa, string marca, string modelo, int anho) {
            TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest inValue = new TransitSoftBusiness.VehiculoWS.modificarVehiculoRequest();
            inValue.id = id;
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.anho = anho;
            return ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).modificarVehiculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdResponse TransitSoftBusiness.VehiculoWS.Vehiculo.obtenerVehiculoPorId(TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest request) {
            return base.Channel.obtenerVehiculoPorId(request);
        }
        
        public TransitSoftBusiness.VehiculoWS.vehiculoDTO obtenerVehiculoPorId(int id) {
            TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest inValue = new TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest();
            inValue.id = id;
            TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdResponse retVal = ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).obtenerVehiculoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdResponse> TransitSoftBusiness.VehiculoWS.Vehiculo.obtenerVehiculoPorIdAsync(TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest request) {
            return base.Channel.obtenerVehiculoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdResponse> obtenerVehiculoPorIdAsync(int id) {
            TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest inValue = new TransitSoftBusiness.VehiculoWS.obtenerVehiculoPorIdRequest();
            inValue.id = id;
            return ((TransitSoftBusiness.VehiculoWS.Vehiculo)(this)).obtenerVehiculoPorIdAsync(inValue);
        }
    }
}
